### ISSUE TITLE
I Get a bottom Scroll bar in "/dashbord"

### ISSUE THREAD

**Issue by Labhk** [balaji-sivasakthi/InfoSense#2]
I get a bottom scroll bar after I get my article prediction
![image](https://github.com/balaji-sivasakthi/InfoSense/assets/79000376/5b64e28c-2562-487d-af9f-bc10b3666330)

Now predict button and view button are not visible
![image](https://github.com/balaji-sivasakthi/InfoSense/assets/79000376/af7727c8-7086-41ff-9c9c-0092723078a7)

**Comment by balaji-sivasakthi** [comment]
@Labhk Issue fixed
