### ISSUE TITLE
fix:set up nav link and navigate to specific pages   

### ISSUE THREAD

**Issue by iwint** [balaji-sivasakthi/InfoSense#5]
# Issue Title: Navbar Issues

### Problem
I've encountered some issues with the navbar in the project. Currently, all the navigation items are linked to the same GitHub page, which is causing confusion and is not intended behavior.

### Requested Changes
1. Fix the navbar links to point to their respective pages or routes.
2. Create specific pages for the navbar items that currently have no associated pages.

## Steps to Reproduce

1. Navigate to the project's homepage.
2. Observe the navigation bar.
3. Click on the navigation items and note the behavior.

## Expected Behavior

- Each navigation item should link to its respective page or route.
- Navigation items that have no associated pages should not be clickable.

## Contributor Information

- **GitHub Username:** iwint
- **Email:** iwinissacofficial@gmail.com

## Additional Comments

I'd like to contribute to fixing these navbar issues in the project. If needed, I'm also willing to help create the necessary pages for the navbar items that are currently unlinked. Please let me know how I can assist in resolving this issue.

---

**Comment by balaji-sivasakthi** [comment]
@iwint ?
