### ISSUE TITLE
feat:create new login page and implement some auth works

### ISSUE THREAD

**Issue by iwint** [balaji-sivasakthi/InfoSense#6]
# Feature Request - Implement Login Page and Authentication in FastAPI

### Summary
I propose the addition of a new login page and the implementation of authentication and authorization features in our existing FastAPI project. This feature is essential for enhancing the security and user experience of our application.

### Feature Details

**1. Login Page:**
- Create a user-friendly login page where users can enter their credentials (e.g., username and password) to access the application.
- Implement validation and error handling for login attempts, providing informative feedback to users.

**2. Authentication:**
- Integrate authentication mechanisms (e.g., JWT tokens) to secure our API endpoints.
- Verify user identity during login and generate tokens for authenticated sessions.
- Implement token validation to prevent unauthorized access to protected routes.

**3. Authorization:**
- Define role-based or permission-based authorization policies.
- Ensure that users can only access resources and perform actions that they are authorized to.
- Implement middleware or decorators to enforce authorization checks on API endpoints.

### Use Cases

- Secure access to sensitive user data and actions within our application.
- Ensure that only authenticated and authorized users can perform specific operations.
- Enhance the overall security of our FastAPI backend.

## Contributor Information

- **GitHub Username:** iwint
- **Email:** iwinissacofficial@gmail.com

## Additional Comments

I'm excited to propose the addition of a login page and the implementation of authentication and authorization features to our FastAPI project. These enhancements will greatly benefit the security and functionality of our application. I look forward to discussions and collaboration on this feature request.

---

**Comment by balaji-sivasakthi** [comment]
@iwint ?
